import React from 'react';
import {
  Flashlight,
  Compass,
  Crosshair,
  Ruler,
  Maximize,
  Navigation,
  Mountain,
  Gauge,
  Thermometer,
  Activity,
  Zap,
  MapPin,
  Magnet,
  Radio,
  QrCode,
  Eye,
  Mic,
  Volume2,
  Sparkles,
  Smile,
  Music,
  Timer,
  ArrowLeftRight,
  Send,
  Monitor,
  Cpu,
  Server,
  Layers,
  FileSpreadsheet,
} from 'lucide-react';
import { ActiveToolId, ToolCategory } from '../types';

export interface RegisteredTool {
  id: ActiveToolId;
  name: string;
  shortName: string;
  category: ToolCategory;
  categoryName: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  accentColor: string;
  angleDeg: number;
}

export const CATEGORIES: { id: ToolCategory; label: string; icon: string }[] = [
  { id: 'lighting', label: 'Oświetlenie & Sygnały', icon: 'Flashlight' },
  { id: 'measurement', label: 'Pomiary & Geometria', icon: 'Ruler' },
  { id: 'navigation', label: 'Nawigacja & Pozycja', icon: 'Navigation' },
  { id: 'environment', label: 'Środowisko & Pogoda', icon: 'Thermometer' },
  { id: 'detection', label: 'Pola & Detekcja', icon: 'Magnet' },
  { id: 'optics', label: 'Optyka & Obraz', icon: 'Eye' },
  { id: 'sound', label: 'Dźwięk & Akustyka', icon: 'Mic' },
  { id: 'utilities', label: 'Narzędzia & System', icon: 'Cpu' },
  { id: 'workshop', label: 'Druk 3D & Klipper', icon: 'Server' },
];

export const ALL_TOOLS: RegisteredTool[] = [
  // 1. Latarka
  {
    id: 'flashlight',
    name: 'Latarka & Oświetlenie Ekranem',
    shortName: 'Latarka',
    category: 'lighting',
    categoryName: 'Oświetlenie',
    description: 'Dioda LED z suwakiem jasności, stroboskopem, SOS i świeceniem ekranu RGB',
    icon: Flashlight,
    accentColor: 'text-amber-400 border-amber-500/40 bg-amber-500/10',
    angleDeg: 0,
  },
  // 2. Poziomica
  {
    id: 'bubble_level',
    name: 'Poziomica Bąbelkowa 2D/3D',
    shortName: 'Poziomica',
    category: 'measurement',
    categoryName: 'Pomiary',
    description: 'Dokładny kąt nachylenia płaszczyzny i pionu z kalibracją Tare, w stopniach i mm/m',
    icon: Compass,
    accentColor: 'text-indigo-400 border-indigo-500/40 bg-indigo-500/10',
    angleDeg: 14,
  },
  // 3. Kątomierz
  {
    id: 'protractor',
    name: 'Kątomierz Ekranowy & Kamera AR',
    shortName: 'Kątomierz',
    category: 'measurement',
    categoryName: 'Pomiary',
    description: 'Precyzyjny pomiar kątów z ramionami wskaźnika na ekranie lub z podglądem z kamery',
    icon: Crosshair,
    accentColor: 'text-indigo-400 border-indigo-500/40 bg-indigo-500/10',
    angleDeg: 28,
  },
  // 4. Linijka
  {
    id: 'ruler',
    name: 'Linijka Ekranowa & Suwmiarka',
    shortName: 'Linijka',
    category: 'measurement',
    categoryName: 'Pomiary',
    description: 'Podziałka w centymetrach i calach z suwakami pomiaru calipera do 0.1 mm',
    icon: Ruler,
    accentColor: 'text-indigo-400 border-indigo-500/40 bg-indigo-500/10',
    angleDeg: 42,
  },
  // 5. Pomiary przestrzenne AR
  {
    id: 'ar_measure',
    name: 'Pomiary Przestrzenne AR',
    shortName: 'Pomiary AR',
    category: 'measurement',
    categoryName: 'Pomiary',
    description: 'Wyznaczanie odległości, powierzchni m² i kubatury m³ za pomocą kamery i czujników',
    icon: Maximize,
    accentColor: 'text-indigo-400 border-indigo-500/40 bg-indigo-500/10',
    angleDeg: 55,
  },
  // 6. Kompas
  {
    id: 'compass',
    name: 'Kompas Magnetyczny & AR HUD',
    shortName: 'Kompas',
    category: 'navigation',
    categoryName: 'Nawigacja',
    description: 'Wskazanie kierunków świata 360°, azymut magnetyczny i podgląd na żywo z kamery',
    icon: Navigation,
    accentColor: 'text-sky-400 border-sky-500/40 bg-sky-500/10',
    angleDeg: 69,
  },
  // 7. Wysokościomierz
  {
    id: 'altimeter',
    name: 'Wysokościomierz (Altimeter)',
    shortName: 'Wysokościomierz',
    category: 'navigation',
    categoryName: 'Nawigacja',
    description: 'Wysokość n.p.m. z GPS i barometru oraz wysokościomierz względny z zerowaniem QFE',
    icon: Mountain,
    accentColor: 'text-sky-400 border-sky-500/40 bg-sky-500/10',
    angleDeg: 83,
  },
  // 8. Barometr
  {
    id: 'barometer',
    name: 'Barometr Atmosferyczny',
    shortName: 'Barometr',
    category: 'environment',
    categoryName: 'Środowisko',
    description: 'Odczyt ciśnienia w hPa/mmHg, wykres trendu barycznego i tendencja pogody',
    icon: Gauge,
    accentColor: 'text-teal-400 border-teal-500/40 bg-teal-500/10',
    angleDeg: 97,
  },
  // 9. Termometr i higrometr
  {
    id: 'thermometer_hygrometer',
    name: 'Termometr & Higrometr (Punkt Rosy)',
    shortName: 'Termo/Higro',
    category: 'environment',
    categoryName: 'Środowisko',
    description: 'Temperatura, wilgotność względna RH%, punkt rosy i pobieranie stacji pogodowej na żywo',
    icon: Thermometer,
    accentColor: 'text-teal-400 border-teal-500/40 bg-teal-500/10',
    angleDeg: 111,
  },
  // 10. Sejsmograf
  {
    id: 'seismograph',
    name: 'Sejsmograf & Wibrometr',
    shortName: 'Sejsmograf',
    category: 'environment',
    categoryName: 'Środowisko',
    description: 'Monitorowanie wstrząsów i drgań w czasie rzeczywistym z wykresem 3D i skalą intensywności',
    icon: Activity,
    accentColor: 'text-rose-400 border-rose-500/40 bg-rose-500/10',
    angleDeg: 125,
  },
  // 11. Szybkościomierz
  {
    id: 'speedometer',
    name: 'Szybkościomierz GPS (Speedometer)',
    shortName: 'Prędkościomierz',
    category: 'navigation',
    categoryName: 'Nawigacja',
    description: 'Prędkość w km/h, mph, węzłach, prędkość maksymalna, średnia i licznik trasy',
    icon: Zap,
    accentColor: 'text-sky-400 border-sky-500/40 bg-sky-500/10',
    angleDeg: 138,
  },
  // 12. GPS Finder
  {
    id: 'gps_finder',
    name: 'GPS i Geolokalizator',
    shortName: 'GPS Pozycja',
    category: 'navigation',
    categoryName: 'Nawigacja',
    description: 'Współrzędne dziesiętne i DMS, dokładność pomiaru, wysokość i udostępnianie pozycji',
    icon: MapPin,
    accentColor: 'text-sky-400 border-sky-500/40 bg-sky-500/10',
    angleDeg: 152,
  },
  // 13. Detektor metalu
  {
    id: 'metal_detector',
    name: 'Detektor Metalu (Pinpointer)',
    shortName: 'Wykrywacz Metalu',
    category: 'detection',
    categoryName: 'Detekcja',
    description: 'Wykrywanie ferromagnetyków i kabli z pikania dźwiękowego i kalibracją tła Tare',
    icon: Magnet,
    accentColor: 'text-rose-400 border-rose-500/40 bg-rose-500/10',
    angleDeg: 166,
  },
  // 14. EMF Meter
  {
    id: 'emf_meter',
    name: 'Miernik Pola EMF (Elektrosmog)',
    shortName: 'Miernik EMF',
    category: 'detection',
    categoryName: 'Detekcja',
    description: 'Skanowanie promieniowania elektromagnetycznego w µT i mG, strefy bezpieczeństwa ICNIRP',
    icon: Radio,
    accentColor: 'text-rose-400 border-rose-500/40 bg-rose-500/10',
    angleDeg: 180,
  },
  // 15. Skaner QR i kodów
  {
    id: 'qr_barcode_scanner',
    name: 'Skaner Kodów Kreskowych & QR',
    shortName: 'Skaner QR/Kody',
    category: 'optics',
    categoryName: 'Optyka',
    description: 'Błyskawiczne odczytywanie kodów QR, EAN-13, UPC z kamery, latarka i historia odczytów',
    icon: QrCode,
    accentColor: 'text-emerald-400 border-emerald-500/40 bg-emerald-500/10',
    angleDeg: 194,
  },
  // 16. Lupa z filtrami
  {
    id: 'magnifier',
    name: 'Lupa Makro (Focus & Filtry)',
    shortName: 'Lupa Makro',
    category: 'optics',
    categoryName: 'Optyka',
    description: 'Powiększenie do 10x, manual focus, zamrażanie kadru, podświetlenie Focus Peaking',
    icon: Eye,
    accentColor: 'text-emerald-400 border-emerald-500/40 bg-emerald-500/10',
    angleDeg: 208,
  },
  // 17. Decybelomierz
  {
    id: 'sound_meter',
    name: 'Decybelomierz SPL & Analizator dB',
    shortName: 'Decybelomierz',
    category: 'sound',
    categoryName: 'Dźwięk',
    description: 'Natężenie hałasu w decybelach (SPL dB) z mikrofonu z min/max i wykresem widma',
    icon: Mic,
    accentColor: 'text-amber-400 border-amber-500/40 bg-amber-500/10',
    angleDeg: 222,
  },
  // 18. Generator częstotliwości
  {
    id: 'frequency_generator',
    name: 'Generator Częstotliwości Audio',
    shortName: 'Generator Hz',
    category: 'sound',
    categoryName: 'Dźwięk',
    description: 'Generowanie fal (sinus, trójkąt, prostokąt, piła) 20Hz - 20kHz, sweep i test głośników',
    icon: Volume2,
    accentColor: 'text-amber-400 border-amber-500/40 bg-amber-500/10',
    angleDeg: 235,
  },
  // 19. Stroboskop
  {
    id: 'strobe_light',
    name: 'Stroboskop & Generator Błysków',
    shortName: 'Stroboskop',
    category: 'lighting',
    categoryName: 'Oświetlenie',
    description: 'Błyski diodą LED lub ekranem o zadanej częstotliwości w Hz lub RPM obrotomierza',
    icon: Sparkles,
    accentColor: 'text-amber-400 border-amber-500/40 bg-amber-500/10',
    angleDeg: 249,
  },
  // 20. Lustro
  {
    id: 'mirror',
    name: 'Lustro z Przedniej Kamery',
    shortName: 'Lustro',
    category: 'optics',
    categoryName: 'Optyka',
    description: 'Podgląd z kamery przedniej z doświetlającą ramką LED, zamrażaniem obrazu i zoomem',
    icon: Smile,
    accentColor: 'text-emerald-400 border-emerald-500/40 bg-emerald-500/10',
    angleDeg: 263,
  },
  // 21. Metronom i stroik
  {
    id: 'metronome_tuner',
    name: 'Metronom & Stroik Muzyczny',
    shortName: 'Metronom/Stroik',
    category: 'sound',
    categoryName: 'Dźwięk',
    description: 'Wybijanie tempa (BPM 30-300, metrum) oraz stroik chromatyczny z detekcją Hz i nut',
    icon: Music,
    accentColor: 'text-amber-400 border-amber-500/40 bg-amber-500/10',
    angleDeg: 277,
  },
  // 22. Stoper i minutnik
  {
    id: 'stopwatch_timer',
    name: 'Stoper & Minutnik Warsztatowy',
    shortName: 'Stoper/Minutnik',
    category: 'utilities',
    categoryName: 'Narzędzia',
    description: 'Precyzyjny stoper z międzyczasami (okrążenia) oraz minutnik z alarmem',
    icon: Timer,
    accentColor: 'text-cyan-400 border-cyan-500/40 bg-cyan-500/10',
    angleDeg: 291,
  },
  // 23. Przelicznik jednostek
  {
    id: 'unit_converter',
    name: 'Przelicznik Jednostek & Walut',
    shortName: 'Przelicznik',
    category: 'utilities',
    categoryName: 'Narzędzia',
    description: 'Konwersja długości, wagi, ciśnienia, temperatury, prędkości oraz kalkulator walut',
    icon: ArrowLeftRight,
    accentColor: 'text-cyan-400 border-cyan-500/40 bg-cyan-500/10',
    angleDeg: 305,
  },
  // 24. Latarka Morse'a
  {
    id: 'morse_code',
    name: 'Latarka & Nadajnik Morse\'a',
    shortName: 'Kod Morse\'a',
    category: 'lighting',
    categoryName: 'Oświetlenie',
    description: 'Automatyczne nadawanie tekstu alfabetem Morse\'a światłem LED/ekranu i dźwiękiem',
    icon: Send,
    accentColor: 'text-amber-400 border-amber-500/40 bg-amber-500/10',
    angleDeg: 318,
  },
  // 25. Test ekranu
  {
    id: 'screen_tester',
    name: 'Test Pikseli & Ekranu Dotykowego',
    shortName: 'Test Ekranu',
    category: 'utilities',
    categoryName: 'Narzędzia',
    description: 'Diagnostyka martwych pikseli (RGB/White/Black), równomierności podświetlenia i dotyku',
    icon: Monitor,
    accentColor: 'text-cyan-400 border-cyan-500/40 bg-cyan-500/10',
    angleDeg: 332,
  },
  // 26. Device info
  {
    id: 'device_info',
    name: 'Informacje o Urządzeniu & Systemie',
    shortName: 'Info o Systemie',
    category: 'utilities',
    categoryName: 'Narzędzia',
    description: 'Podgląd procesora, pamięci RAM, stanu baterii, ekranu, sieci i czujników',
    icon: Cpu,
    accentColor: 'text-cyan-400 border-cyan-500/40 bg-cyan-500/10',
    angleDeg: 346,
  },
  // Moduły druku 3D
  {
    id: 'input_shaper',
    name: 'Input Shaper 3D (FFT Akcelerometru)',
    shortName: 'Input Shaper',
    category: 'workshop',
    categoryName: 'Druk 3D',
    description: 'Analiza rezonansu osi X/Y drukarki 3D i generowanie filtrów Klipper MZV/EI',
    icon: Activity,
    accentColor: 'text-orange-400 border-orange-500/40 bg-orange-500/10',
    angleDeg: 270,
  },
  {
    id: 'belt_tuner',
    name: 'Tuner Naciągu Pasków GT2',
    shortName: 'Tuner Pasków',
    category: 'workshop',
    categoryName: 'Druk 3D',
    description: 'Akustyczny analizator Hz naciągu pasków z presetami Voron, Ender, Prusa',
    icon: Gauge,
    accentColor: 'text-orange-400 border-orange-500/40 bg-orange-500/10',
    angleDeg: 285,
  },
  {
    id: 'klipper_dashboard',
    name: 'Panel Klipper & Moonraker',
    shortName: 'Panel Klipper',
    category: 'workshop',
    categoryName: 'Druk 3D',
    description: 'Podgląd stanu drukarki 3D, temperatur dyszy/stołu i konsola poleceń',
    icon: Server,
    accentColor: 'text-orange-400 border-orange-500/40 bg-orange-500/10',
    angleDeg: 255,
  },
  {
    id: 'logs_manager',
    name: 'Menedżer Logów Pomiarowych',
    shortName: 'Logi CSV',
    category: 'utilities',
    categoryName: 'Narzędzia',
    description: 'Eksport sesji do CSV, pobieranie i udostępnianie danych pomiarowych',
    icon: FileSpreadsheet,
    accentColor: 'text-slate-400 border-slate-700 bg-slate-800/80',
    angleDeg: 355,
  },
];
